"""
Jawab — AI Review Responder
Paste a G2/Capterra review → get a professional, empathetic reply via Llama3 (Ollama)

Usage:
    python jawab.py

Requirements:
    pip install ollama
    ollama pull llama3
"""

import ollama
import textwrap

# ── Config ──────────────────────────────────────────────────────────────────
MODEL = "llama3"
PRODUCT_NAME = "YourProduct"   # Change this to your SaaS product name
COMPANY_NAME = "YourCompany"   # Change this to your company name

SYSTEM_PROMPT = f"""
You are a senior Customer Success Manager at {COMPANY_NAME}, responding to a public review
of {PRODUCT_NAME} on G2 or Capterra.

Your job is to write a professional, warm, and genuine reply to the review.

Rules:
- Always thank the reviewer, whether the review is positive or negative
- For negative reviews: acknowledge the pain point specifically, apologise sincerely, and offer a concrete next step (e.g. reach out to support, a fix is in progress)
- For positive reviews: express genuine gratitude, highlight one thing they mentioned, and invite them to explore a feature they might not know about
- Never be defensive or dismissive
- Keep the tone human — not corporate-robotic
- Length: 4–6 sentences max
- Do NOT start with "Dear User" or generic openers — reference something specific from the review

Output format:
SENTIMENT: [Positive / Negative / Mixed]
RATING GUESS: [1–5 stars]
REPLY:
[Your response here]
""".strip()

# ── Helpers ──────────────────────────────────────────────────────────────────

def print_banner():
    print("\n" + "═" * 58)
    print("  🗣️  JAWAB — AI Review Responder")
    print("  Powered by Llama3 via Ollama")
    print("═" * 58 + "\n")

def get_review_input():
    print("Paste the customer review below.")
    print("When done, press Enter twice:\n")
    lines = []
    while True:
        line = input()
        if line == "" and lines and lines[-1] == "":
            break
        lines.append(line)
    return "\n".join(lines).strip()

def analyze_review(review_text: str) -> str:
    response = ollama.chat(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Here is the review:\n\n{review_text}"}
        ]
    )
    return response["message"]["content"]

def print_result(result: str):
    print("\n" + "─" * 58)
    print("  JAWAB ANALYSIS")
    print("─" * 58)
    for line in result.strip().split("\n"):
        if line.startswith("SENTIMENT:") or line.startswith("RATING GUESS:"):
            print(f"  {line}")
        elif line.startswith("REPLY:"):
            print(f"\n  REPLY:")
        else:
            # Word-wrap the reply body at 54 chars
            wrapped = textwrap.fill(line, width=54)
            for wline in wrapped.split("\n"):
                print(f"    {wline}")
    print("\n" + "─" * 58 + "\n")

# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print_banner()

    # Check Ollama is running
    try:
        ollama.list()
    except Exception:
        print("❌  Cannot connect to Ollama.")
        print("    Make sure Ollama is running: `ollama serve`")
        print("    And Llama3 is pulled: `ollama pull llama3`\n")
        return

    review = get_review_input()

    if not review:
        print("⚠️  No review entered. Exiting.\n")
        return

    print("\n⏳  Generating reply...\n")

    try:
        result = analyze_review(review)
        print_result(result)
    except Exception as e:
        print(f"\n❌  Error calling Llama3: {e}\n")

    # Loop — respond to another review?
    again = input("  Respond to another review? (y/n): ").strip().lower()
    if again == "y":
        print()
        main()
    else:
        print("\n  Done. Replies generated by Jawab. 🎯\n")

if __name__ == "__main__":
    main()
